### ISSUE TITLE
有2个疑问点

### ISSUE THREAD

**Issue by zhanxiage1994** [mouna99/dien#11]
1. build_fcn_net中， ctr_loss为啥只考虑正样本概率？常规cross_enproty是 ylog(y')+(1-y)log(1-y')， 代码中貌似没有1-y部分？
2. 代码中所有tf.layers.batch_normalization，都没有考虑training这个参数项，在做预测时会有问题吧？

**Comment by sudongxiang** [comment]
2.  batch_normalization 用法确实有问题,@mouna99 ，跟@zhougr1993  的一样，自己可以加上，网上能搜到的。@zhanxiage1994，https://www.jianshu.com/p/ec4fc42fd488  这个是解决方案。

**Comment by sudongxiang** [comment]
（1）ctr_loss 应该是label为1和-1，而我们常见的是0和1，所以，这里自己改过来即可，跟label有关系。label不同，交叉熵损失写法不同。
（2）确实，这是一个bug；
