### ISSUE TITLE
无法在Books数据集中复现0.9281的AUC

### ISSUE THREAD

**Issue by wyljpn** [mouna99/dien#21]
我下载了源代码，在实验室的服务器做了实验，想要复现实验结果。可是无法得到论文中Table 2: Results(AUC) on public datasets中的Books(AUC) DIEN 0.9281的结果。

itr: 0
iter: 1000 ----> train_loss: 1.6092 ---- train_accuracy: 0.5897 ---- tran_aux_loss: 1.2785
test_auc: 0.6695 ----test_loss: 1.5685 ---- test_accuracy: 0.6192 ---- test_aux_loss: 1.3612
iter: 2000 ----> train_loss: 1.5228 ---- train_accuracy: 0.6465 ---- tran_aux_loss: 1.2142
test_auc: 0.7304 ----test_loss: 1.4456 ---- test_accuracy: 0.6646 ---- test_aux_loss: 1.3199
iter: 3000 ----> train_loss: 1.4194 ---- train_accuracy: 0.6822 ---- tran_aux_loss: 1.1306
test_auc: 0.7627 ----test_loss: 1.3634 ---- test_accuracy: 0.6907 ---- test_aux_loss: 1.2456
iter: 4000 ----> train_loss: 1.3485 ---- train_accuracy: 0.7085 ---- tran_aux_loss: 1.0726
test_auc: 0.7847 ----test_loss: 1.3135 ---- test_accuracy: 0.7130 ---- test_aux_loss: 1.2510
iter: 5000 ----> train_loss: 1.3035 ---- train_accuracy: 0.7262 ---- tran_aux_loss: 1.0380
test_auc: 0.8018 ----test_loss: 1.2749 ---- test_accuracy: 0.7249 ---- test_aux_loss: 1.1818
save model iter: 5000
iter: 6000 ----> train_loss: 1.2689 ---- train_accuracy: 0.7381 ---- tran_aux_loss: 1.0113
test_auc: 0.8163 ----test_loss: 1.2417 ---- test_accuracy: 0.7382 ---- test_aux_loss: 1.1733
iter: 7000 ----> train_loss: 1.2372 ---- train_accuracy: 0.7471 ---- tran_aux_loss: 0.9857
test_auc: 0.8218 ----test_loss: 1.2169 ---- test_accuracy: 0.7469 ---- test_aux_loss: 1.1991
iter: 8000 ----> train_loss: 1.2099 ---- train_accuracy: 0.7556 ---- tran_aux_loss: 0.9644
test_auc: 0.8337 ----test_loss: 1.1918 ---- test_accuracy: 0.7550 ---- test_aux_loss: 1.1223
itr: 1
iter: 9000 ----> train_loss: 0.5829 ---- train_accuracy: 0.4106 ---- tran_aux_loss: 0.4726
test_auc: 0.8269 ----test_loss: 1.2050 ---- test_accuracy: 0.7483 ---- test_aux_loss: 1.1159
iter: 10000 ----> train_loss: 1.0740 ---- train_accuracy: 0.8471 ---- tran_aux_loss: 0.9013
test_auc: 0.8137 ----test_loss: 1.2136 ---- test_accuracy: 0.7356 ---- test_aux_loss: 1.1241
save model iter: 10000
iter: 11000 ----> train_loss: 1.0228 ---- train_accuracy: 0.8775 ---- tran_aux_loss: 0.8820
test_auc: 0.8243 ----test_loss: 1.2259 ---- test_accuracy: 0.7446 ---- test_aux_loss: 1.0999
iter: 12000 ----> train_loss: 0.9986 ---- train_accuracy: 0.8885 ---- tran_aux_loss: 0.8711
test_auc: 0.8330 ----test_loss: 1.2076 ---- test_accuracy: 0.7512 ---- test_aux_loss: 1.0986
iter: 13000 ----> train_loss: 0.9614 ---- train_accuracy: 0.9066 ---- tran_aux_loss: 0.8539
test_auc: 0.8410 ----test_loss: 1.2085 ---- test_accuracy: 0.7606 ---- test_aux_loss: 1.1340
iter: 14000 ----> train_loss: 0.9401 ---- train_accuracy: 0.9136 ---- tran_aux_loss: 0.8409
test_auc: 0.8434 ----test_loss: 1.2056 ---- test_accuracy: 0.7654 ---- test_aux_loss: 1.1038
iter: 15000 ----> train_loss: 0.9175 ---- train_accuracy: 0.9261 ---- tran_aux_loss: 0.8309
test_auc: 0.8431 ----test_loss: 1.2477 ---- test_accuracy: 0.7663 ---- test_aux_loss: 1.1385
save model iter: 15000
iter: 16000 ----> train_loss: 0.8970 ---- train_accuracy: 0.9295 ---- tran_aux_loss: 0.8152
test_auc: 0.8467 ----test_loss: 1.2512 ---- test_accuracy: 0.7694 ---- test_aux_loss: 1.1397
itr: 2
iter: 17000 ----> train_loss: 0.0262 ---- train_accuracy: 0.0251 ---- tran_aux_loss: 0.0228
test_auc: 0.8428 ----test_loss: 1.2087 ---- test_accuracy: 0.7651 ---- test_aux_loss: 1.1152
iter: 18000 ----> train_loss: 0.9043 ---- train_accuracy: 0.9177 ---- tran_aux_loss: 0.8047
test_auc: 0.8289 ----test_loss: 1.3211 ---- test_accuracy: 0.7490 ---- test_aux_loss: 1.0893
iter: 19000 ----> train_loss: 0.8561 ---- train_accuracy: 0.9534 ---- tran_aux_loss: 0.7959
test_auc: 0.8239 ----test_loss: 1.3750 ---- test_accuracy: 0.7371 ---- test_aux_loss: 1.0886
iter: 20000 ----> train_loss: 0.8327 ---- train_accuracy: 0.9670 ---- tran_aux_loss: 0.7909
test_auc: 0.8389 ----test_loss: 1.3757 ---- test_accuracy: 0.7550 ---- test_aux_loss: 1.1187
save model iter: 20000
iter: 21000 ----> train_loss: 0.8127 ---- train_accuracy: 0.9748 ---- tran_aux_loss: 0.7810
test_auc: 0.8461 ----test_loss: 1.3983 ---- test_accuracy: 0.7636 ---- test_aux_loss: 1.0857
iter: 22000 ----> train_loss: 0.7974 ---- train_accuracy: 0.9779 ---- tran_aux_loss: 0.7694
test_auc: 0.8453 ----test_loss: 1.4055 ---- test_accuracy: 0.7637 ---- test_aux_loss: 1.1258
iter: 23000 ----> train_loss: 0.7831 ---- train_accuracy: 0.9799 ---- tran_aux_loss: 0.7575
test_auc: **0.8501** ----test_loss: 1.3910 ---- test_accuracy: 0.7702 ---- test_aux_loss: 1.1075
iter: 24000 ----> train_loss: 0.7664 ---- train_accuracy: 0.9822 ---- tran_aux_loss: 0.7434
test_auc: 0.8459 ----test_loss: 1.4197 ---- test_accuracy: 0.7682 ---- test_aux_loss: 1.1221
iter: 25000 ----> train_loss: 0.7561 ---- train_accuracy: 0.9848 ---- tran_aux_loss: 0.7362
test_auc: 0.8432 ----test_loss: 1.4291 ---- test_accuracy: 0.7650 ---- test_aux_loss: 1.1176
save model iter: 25000

可以观察到训练过程中的test_auc最高为0.8501。此外，可以观察到模型出现了过拟合的情况，因为可以看到train_accuracy虽然持续上升，test_accuracy最高是停留在了0.77附近。我也训练和测试了dien-master中的DIN模型，最好的test_auc也只有0.7336，test_accuracy最高是停留在了0.66附近。
       对此我觉得有点奇怪，我阅读了代码，注意到在生成数据过程的其中一个步骤，split_by_user.py中是使用"local_test"而不是"local_train"来生成“local_train_splitByUser”和“local_test_splitByUser”  。我觉得有可能是训练样本不够，于是使用"local_train"来生成“local_train_splitByUser”和“local_test_splitByUser”来训练。但是结果并没有改善，甚至有所下降。
       我是按照https://github.com/mouna99/dien的README来操作，采用method 1来生成数据。除了添加注释、日志和指定GPU之外，没有更改核心代码。为什么得不到论文中记录的0.9281的AUC呢，我很奇怪。能否请您赐教？如果您能赐教，我将非常感激！

**Comment by mouna99** [comment]
之前的数据处理方式有些不合理，我们更新了数据处理的方式，和论文的表格。
![image](https://user-images.githubusercontent.com/14691768/55934755-38be6e80-5c64-11e9-9aa9-d765861cf9dd.png)
