### ISSUE TITLE
split_by_user with file local_test???

### ISSUE THREAD

**Issue by huzuoliang** [mouna99/dien#42]
阅读local_aggretor.py，生成了文件
ftrain = open("local_train", "w")
ftest = open("local_test", "w")

但在split_by_user.py中，用local_test文件生成训练和测试文件：
ftrain = open("local_train_splitByUser", "w")
ftest = open("local_test_splitByUser", "w")
这是什么神奇操作???

**Comment by FightingMeow** [comment]
The same question ...
