### ISSUE TITLE
关于辅助损失函数

### ISSUE THREAD

**Issue by DoubleYing** [mouna99/dien#7]
为什么在计算辅助损失函数是，click_prob和noclick_prob都只需辅助网络结果为0的概率呢？
不应该是click_prop取1的概率，noclick_prob取0的概率，然后使得两者的损失和最小么?

**Comment by mouna99** [comment]
实际上算的就是click_prop取1的概率，noclick_prob取0的概率，仔细看代码
`click_loss_ = - tf.reshape(tf.log(click_prop_), [-1, tf.shape(click_seq)[1]]) * mask`
   `noclick_loss_ = - tf.reshape(tf.log(1.0 - noclick_prop_), [-1, tf.shape(noclick_seq)[1]]) * mask`
