### ISSUE TITLE
In DIN model , The Out Product make me confused

### ISSUE THREAD

**Issue by sshzhang** [mouna99/dien#8]
From your model DIN, When you get the different user  representation respect to different item., you use Out Product ,  This attention operation make me confused.   Have you try other operation. such as direct send the concat  vector to feed forward network!

**Comment by mouna99** [comment]
attention有多种形式，我们也都用过，这里选择的是和上一篇paper DIN一样的实现方式，方便对比吧。

**Comment by liduo1997** [comment]
outer product 维度对不上呀
